name = "meetus"
main = "src/index.js"
compatibility_date = "2024-02-20"

[[durable_objects.bindings]]
name = "MEETING_ROOM"
class_name = "MeetingRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MeetingRoom"]
